<p>This function can add extra keywords in your content, to boost its keyword
    density.</p>

<p><strong>Use general setting:</strong> If you select this, then whatever you
    have selected in the
    <a href="<?php echo admin_url('admin.php?page=OnPageSeo-options'); ?>">options</a>
    screen will take effect. If you later change the settings from the options
    screen, then those changes will immediatelly take effect in the post/page
    itself.</p>

<p><strong>Throughout the content:</strong> If you select this, and your desired
    keyword doesn't appear enough times in your content to satisfy all SEO
    factors, then the keyword will be added several times between paragraphs and
    also become optimized, untill all the SEO factors you have selected are
    satisfied. For example, it will add the term once in H1 and once in H2, if
    these two factors weren't present in your content. This option will look
    more natural to the search engines, but may look odd to some of the
    visitors, because the content will be &quot;interrupted&quot; by the keyword
    a few times.</p>

<p><strong>At the bottom of the content:</strong> If you select this, and your
    desired keyword doesn't appear enough times in your content to satisfy all
    SEO factors, then the keyword will be added several times at the bottom of
    the content and also become optimized, untill all the SEO factors you have
    selected are satisfied. For example, it will add the term once in H1 and
    once in H2, if these two factors weren't present in your content. This
    option will look more natural to your blog visitors, but may look a little
    odd to the search engines, because the keyword will appear at the bottom of
    the content several times.</p>

<p><strong>Don't add extra keywords:</strong> If you select this, then the
    existing keywords in your content will be optimized, but no extra keywords
    will be added throughout the content. This option is probably the best one.
    It allows for a &quot;good&quot; amount of optimization, while avoiding
    &quot;overoptimization&quot; that search engines like Google have come to
    penalize.</p>