<p>If you haven't created some posts or pages yet. but you want them to be
    optimized automatically when you do, select the options below.</p>

<p>You can choose to optimize the content based on the title, or on a specific
    keyword you specify.</p>

<p>This will only affect posts or pages that you haven't created already. It
    will not affect posts or pages that have already been scheduled or
    published.</p>