<p>In order to add related terms to the bottom of your posts, you will need a
FREE Bing Search API key.</p>

<p>To get your FREE Bing Search API key
    <a href="https://datamarket.azure.com/dataset/5BA839F1-12CE-4CCE-BF57-A49D98D29A44" target="_blank">sign up here</a>.</p>

<p>Choose the free &quot;5,000 transactions/month plan&quot;.</p>

<p>After you sign up, make sure you are signed in to the URL above and you will
be able to find your API key under <a href="https://datamarket.azure.com/account/info" target="_blank">My Account</a>
==&gt; Primary Account Key.</p>

<p>The API key will look something like:</p>

<pre>P+bROx5gTQy6giz1o4IN2U7O1d6v3vVlZKW9kUyAaMc=</pre>
