<p>Enter the title that you want the homepage of your site to be optimized
    for.</p>

<p>This option will only work if you are using the default WordPress option and
    showing your most recent posts as your homepage.</p>

<p>If you have set a static page to be your homepage, then the title of that
    page will be the meta title of your homepage.</p>

<p>You can change this option on your
    <a href="<?php echo admin_url('options-reading.php'); ?>" target="_blank">reading settings</a>
    page.</p>